#!/bin/bash

_whisparr_version() {
    if whisparrv="$(/usr/bin/mono /opt/Whisparr/Whisparr.exe \? |& head -n 1 | grep -Eo "Version(.*)$")"; then
        [[ "$whisparrv" =~ ^(Version 1.0.(.*))$ ]] && echo "mono-v1"
    elif whisparrv="$(/opt/Whisparr/Whisparr \? |& head -n 1 | grep -Eo "Version(.*)$")"; then
        [[ "$whisparrv" =~ ^(Version 1.0.(.*))$ ]] && echo "netcore-v1"
    else
        echo_log_only "Whisparr Version Error: No version could be determined"
    fi
}
